### ISSUE TITLE
实现元素水平垂直布局的常用方式

### ISSUE THREAD

**Issue by sgiyy** [sgiyy/blog#20]
## 水平居中的几种实现方法

- margin 和 width 实现水平居中
```css
div {
  width: 200px;
  margin-left: auto;
  margin-right: auto;
}
```

- inline-block 水平居中
```css
.parent {
  text-align: center;
  ...
}
.parent .child {
  display: inline-block;
  ...
}
```
另外，设置为 `display: inline-block;` 的元素之间可能会有间距，解决办法：[如何解决inline-block元素的空白间距](https://www.w3cplus.com/css/fighting-the-space-between-inline-block-elements)

- 绝对定位absolute水平居中

```css
div {
  position: absolute;
  width: 600px;
  left: 50%;
  margin-left: -300px;
}
```

- flex 实现水平居中

```css
.parent {
  display:flex;
  justify-content:center;
}
```

## 垂直居中的几种实现方法

- 单行文本和图片垂直居中： line-height
```css
<p>我是一段垂直居中的文字</p>

p {
  height: 28px;
  line-height: 28px;
}
```

- 绝对定位和负margin 实现垂直居中
```css
div {
  position:absolute;
  top: 50%;
  height: 200px;
  margin-top: -100px;
}
```

- 模拟table特性实现垂直居中
```css
.parent {
  display: table;
}
.parent .child {
  display: table-cell;
  vertical-align: middle;
}
```

## 水平垂直均居中的实现方法

- 绝对定位水平垂直居中，加 `margin: auto`

```css
div{
  position:absolute;
  left:0;
  top: 0;
  bottom: 0;
  right: 0;
  width: 200px;
  height: 200px;
  margin: auto;
}
```

- 绝对定位水平垂直居中，加 margin负值

```css
div{
  position:absolute;
  left:50%;
  top:50%;
  width: 200px;
  height: 200px;
  margin-left:-100px;
  margin-top:-100px;
}
```

- 绝对定位水平垂直居中，加 transform

```css
div{
  position:absolute;
  left:50%;
  top:50%;
  width: 200px;
  height: 200px;
  transform: translate(-50%,-50%);
}
```

- flex 实现不定宽度和高度元素水平垂直居中

```css
.parent {
  display:flex;
  justify-content:center;
  align-items:center;
  ...
}
```
